### ISSUE TITLE
make test target is needed

### ISSUE THREAD

**Issue by jjts** [IObundle/iob-cache#120]
cache should have an individual test and added to Jenkins

**Comment by codingUniv** [comment]
For the last available update on the master branch, 
make run VCD=0 does not run simulation without generating vcd file. 
If you would like to run simulation with or without generating vcd file using only VCD macro, I suggest that you remove
`define VCD
from .vh files of the testbench.
What do you think?

**Comment by jjts** [comment]
I agree

**Comment by jjts** [comment]
I thought they'd already been removed

**Comment by jjts** [comment]
this has been done
