### ISSUE TITLE
Do not close an open gtkwave automatically

### ISSUE THREAD

**Issue by codingUniv** [IObundle/iob-cache#132]
I suggest not to close an open gtkwave automatically when running a new simulation. 
There might be situations when parallel debug sessions are required (different VCD files, different rtl, etc.)

**Comment by jjts** [comment]
Closing and reopening is done to reload the vcd file. It is possible to manually reload the vcd without closing gtkwave, so both options are possible without thinking of other situations. If gtkwave is closed we must also be careful to manually save the current waveforms to display in the .gtkw file. So either option are possible.

As for other situations, they need to be clearly identified as we are not worried about potential scenarios but only about the scenarios that exist now.

**Comment by jjts** [comment]
Ok for the other comments.

**Comment by codingUniv** [comment]
All indicated options are interesting.
In addition, we might need to have parallel debug sessions, for example: analyze the waveforms of a given RTL while running a simulation of another RTL in parallel. The current settings will let the second simulation end by closing the first gtkwave session in order to open a new one. This might be challenging for a user who should not stop the ongoing debug.

**Comment by jjts** [comment]
What is there is good enough

What we really need is the readme and docs

**Comment by jjts** [comment]
Please settle in a mode and documented in the readme. Right now my only interest is that there's a way to visualize waveforms even if not the best

**Comment by jjts** [comment]
After that I will close the issue
