### ISSUE TITLE
[WRITE BACK MODE] Not write to backend memory (flushing cache line) when read miss and dirty data exists in that line.

### ISSUE THREAD

**Issue by jiayi-wang98** [IObundle/iob-cache#256]
Hi there,

I'm trying to run the testbench but it seems that when I switch to WRITE-BACK mode (btw changing `WRITE_POL in the iob-cache_tb.vh will not change the real cache-memory write policy because `WRITE_POL is not passed by the testbench, need to pass this parameter to cache instance), when I read a data and it misses, it will read the data from backend to cache line. However, it seems that if that cache line already has dirty data, it will not flush that and write that to backend. Instead, the dirty data will be directly overwritten and loss. As a result, the test will fail and all the dirty data before read operation will be lost. 

I quickly went over the code of this part and did not find any write-dirty-data operation. Not sure if i was getting anything wrong with my environment/configuration.

Could you please also test the write-back mode in iob-cache_tb.v and check the results? 

Thank you so much.

**Comment by jjts** [comment]
Hi, thanks for letting us know. We will check.

**Comment by jjts** [comment]
We changed line 490 in the file cache-memory.v
Could you check if it solves the problem? Thanks.

**Comment by jiayi-wang98** [comment]
Yes. It works well with the testbench provided. Thank you so much!
