### ISSUE TITLE
WRITE Operations hand shake old and new [is the new iteration of Cache-iob fully functional]?

### ISSUE THREAD

**Issue by atmughrabi** [IObundle/iob-cache#292]
Hello,

First of all, thank you for your efforts! I have a question regarding the Cache write signals handshake. I am trying to understand them in the old and new iterations of cache-IOB. For READS, they are working as intended; I am using Xilinx AXI-VIP.

This is for the new cache: For READS, keep holding the valid till I get the read signal back with rvalid. It seems to be working in simulation.

![image](https://github.com/IObundle/iob-cache/assets/2029843/a5f79133-3a54-4c61-b210-24c6480dd3d0)

Now, for WRITE, There is no valid signal "how to know the writes have committed"; in the old cache, it used to work, then crash the AXI VIP with " AXI4_ERRM_WDATA_STABLE  WDATA must remain stable when WVALID is asserted and WREADY low. Spec section A3.2.1.", but it shows writes on the AXI backend.

Is there a wave example for how writes are conducted, as my testbed and the current GitHub simulation environment are challenging to operate?

Furthermore, the new cache gives these errors when packaging via the Xilinx tool (the fix is to remove the reg from these net types) "[VPL 10-3236] concurrent assignment to a non-net 'data_wstrb_reg_o' is not permitted", this is in cache_front_end file.

**Comment by jjts** [comment]
Hi,

Our simulation was broken after the updates, and I have now fixed it. Can you run our simulation and check it? Please follow the README instructions, as you'll need to clone iob-soc with the cache as a submodule.

**Comment by atmughrabi** [comment]
I managed to run the iob-soc simulations, but there aren't any tests for WRITES (can you point me to those runs). Reads are working perfectly, but I am unsure what is happening at the backend that is breaking Xilinx AXI VIP. I am pushing the writes and ensuring I track the number of them according to the write-through buffer size (32 in this case). The backend is 512-bit/64bit address. Even a single write mingled with reads breaks the simulation with an error like this. I tried both WB and WT cache; different combinations give different issues sometimes hangs.

Also, mixing read/writes ends up corrupting the reads. 

- CACHE_N_WAYS = 1
  - `Fatal]  AXI4_ERRM_WLAST_STABLE  WLAST must remain stable when WVALID is asserted and WREADY low. Spec  section	A3.2.1. `
- CACHE_N_WAYS=2+ : hangs

**Comment by atmughrabi** [comment]
I have added this into the write_fsm for WT mode. It solves the issues for the first tests. But persists on random pressure tests. If you guys have a workaround or an explanation, I will be glad. The main reason for using iob_cache is to avoid AXI interfacing altogether. 

`      reg axi_wlast_reg;

      // always_ff @(posedge clk_i or posedge reset_i) begin
      //    if (reset_i) begin
      //       axi_wlast_reg <= 1'b0;
      //    end else if (state == address && axi_awvalid_int && axi_awready_i) begin
      //       // Assert WLAST for each new write transaction
      //       axi_wlast_reg <= 1'b1;
      //    end else begin
      //       // Reset WLAST after the transaction is accepted
      //       axi_wlast_reg <= 1'b0;
      //    end
      // end

      reg [AXI_LEN_W-1:0] burst_counter; // Counter for the number of transfers in a burst

      // Initialize and manage burst counter and WLAST
      always_ff @(posedge clk_i or posedge reset_i) begin
         if (reset_i) begin
            burst_counter <= 0;
            axi_wlast_reg <= 1'b0;
         end else begin
            if (state == address && axi_awvalid_int && axi_awready_i) begin
               burst_counter <= axi_awlen_o; // Load the burst length
               axi_wlast_reg <= (axi_awlen_o == 0); // For single-transfer bursts
            end else if (state == write && axi_wvalid_int && axi_wready_i) begin
               if (burst_counter > 0) begin
                  burst_counter <= burst_counter - 1;
                  axi_wlast_reg <= (burst_counter == 1); // Set WLAST for the last transfer
               end
            end
         end
      end

      assign axi_wlast_o = axi_wlast_reg;
`

**Comment by atmughrabi** [comment]
In order to address the confusion, it appears that there should be a tight connection between the handshake signals of the IOB-Cache and the AXI VIP. As a solution, it seems that using a unique AXI Register Slice in the Auto-Pipelining IP from Xilinx may be effective in resolving the issue. It's worth noting that a regular register pipeline could cause the simulation to break.
